name: kwlib
version: 1.0.16
description: Widget Library for Kapp. Alls konar sameiginlegt fyrir Flutter Widgets
homepage: 
repository: github.com:marinonjalsson/kwlib.git
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  klib:
    git: 
      url: github.com:marinonjalsson/klib.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

assets:
  - google_fonts/
